/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diabetesnn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wind10
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form JForm
     */
    
    private BP bp;
    private BPLM bplm;
    private DataSet set, train, test;
    private int type;
    private int counter = 0;
    
    public UI() {
        initComponents();
        
        set = new DataSet(8, 1);
        set.readCSV();
        set.handleMissVal();
        set.minMaxNorm();
        //set.shuffle();
        //train = set.createTrainData(0.8f);
        //test = set.createTestData(0.2f);
        
        ButtonTest.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Label_Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelLRate = new javax.swing.JLabel();
        TFieldLRate = new javax.swing.JTextField();
        LabelEpoch = new javax.swing.JLabel();
        TFieldEpoch = new javax.swing.JTextField();
        ButtonTrain = new javax.swing.JButton();
        RadioButtonBP = new javax.swing.JRadioButton();
        RadioButtonBPLM = new javax.swing.JRadioButton();
        LabelTraining = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        LabelSpesifisitas = new javax.swing.JLabel();
        LabelSensitifitas = new javax.swing.JLabel();
        LabelAkurasi = new javax.swing.JLabel();
        LabelPresisi = new javax.swing.JLabel();
        LabelFMeasure = new javax.swing.JLabel();
        ButtonTest = new javax.swing.JButton();
        LabelTesting = new javax.swing.JLabel();
        LabelPelatihan = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Title.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Label_Title.setText("Diagnosa Penyakit Diabetes Menggunakan Jaringan Syaraf Tiruan Backpropagation Levenberg-Marquardt");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelLRate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelLRate.setText("Learning Rate :");

        LabelEpoch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelEpoch.setText("Iterasi :");

        TFieldEpoch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ButtonTrain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ButtonTrain.setText("Training");
        ButtonTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTrainActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonBP);
        RadioButtonBP.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        RadioButtonBP.setText("Backpropagation");

        buttonGroup1.add(RadioButtonBPLM);
        RadioButtonBPLM.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        RadioButtonBPLM.setText("Backpropagation Levenberg-Marquardt");

        LabelTraining.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelTraining.setText("Training Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLRate)
                            .addComponent(LabelEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFieldEpoch)
                            .addComponent(TFieldLRate, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTraining)
                            .addComponent(RadioButtonBP)
                            .addComponent(RadioButtonBPLM)
                            .addComponent(ButtonTrain))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTraining, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLRate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldLRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RadioButtonBP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonBPLM)
                .addGap(18, 18, 18)
                .addComponent(ButtonTrain)
                .addContainerGap())
        );

        TableData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Class", "Output"
            }
        ));
        jScrollPane1.setViewportView(TableData);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelSpesifisitas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelSpesifisitas.setText("Spesifisitas :");

        LabelSensitifitas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelSensitifitas.setText("Sensitifitas :");

        LabelAkurasi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelAkurasi.setText("Akurasi :");

        LabelPresisi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelPresisi.setText("Presisi :");

        LabelFMeasure.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelFMeasure.setText("FMeasure :");

        ButtonTest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ButtonTest.setText("Testing");
        ButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTestActionPerformed(evt);
            }
        });

        LabelTesting.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelTesting.setText("Testing Panel");

        LabelPelatihan.setText("Pelatihan :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTesting)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LabelPresisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(LabelSpesifisitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(ButtonTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelAkurasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(LabelSensitifitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(LabelFMeasure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelPelatihan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPelatihan, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(LabelTesting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAkurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSpesifisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSensitifitas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelPresisi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelFMeasure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LabelData.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private DefaultTableModel SetTable(boolean traindata, boolean isBPLM) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new Object[]{
            "Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Class", "Output"});
        
        if (traindata) {
            int[] outcome = null;
            if(isBPLM) 
                outcome = bplm.getClass_train();
            else
                outcome = bp.getClass_train();
            
            for (int i = 0; i < train.size(); i++) {
                double[] input = train.getInput(i);
                double[] output = train.getOutput(i);
                tableModel.addRow(new Object[]{
                    input[0], input[1], input[2], input[3], input[4], input[5], input[6], input[7], output[0], outcome[i]
                });
            }
        } else {
            int[] outcome = null;
            if(isBPLM) 
                outcome = bplm.getClass_test();
            else
                outcome = bp.getClass_test();
            
            for (int i = 0; i < test.size(); i++) {
                double[] input = test.getInput(i);
                double[] output = test.getOutput(i);
                tableModel.addRow(new Object[]{
                    input[0], input[1], input[2], input[3], input[4], input[5], input[6], input[7], output[0], outcome[i]
                });
            }
        }
        
        return tableModel;
    }

    private void ButtonTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTrainActionPerformed
        // TODO add your handling code here:
        
        if(TFieldLRate.getText().isEmpty() || TFieldEpoch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field kosong. Silahkan masukkan nilai");
        }
        else {
            train = set.createTrainData(0.8f);
            
            double learning_rate = Double.parseDouble(TFieldLRate.getText());
            int maxEpoch = Integer.parseInt(TFieldEpoch.getText());
            
            int n_input = 8, n_hidden = 10, n_output = 1;
            
            if (learning_rate >= 0 && learning_rate <= 1) {
                if (RadioButtonBP.isSelected()) {
                    //ConfusionMatrix cfBP = new ConfusionMatrix();
                    bp = new BP(n_input, n_hidden, n_output);
                    bp.trainBP(train, learning_rate, maxEpoch, 0.01);
                    //bp.trainBP(train, learning_rate, maxEpoch, 0.01, cfBP);
                    TableData.setModel(SetTable(true, false));
                    LabelData.setText("Data Pelatihan");
                    type = 1;
                    LabelPelatihan.setText("Pelatihan : BP");
                    //cfBP.savePerformance2(false, counter);
                    //JOptionPane.showMessageDialog(null, "Training Selesai");
                } else if (RadioButtonBPLM.isSelected()) {
                    //ConfusionMatrix cfBPLM = new ConfusionMatrix();
                    bplm = new BPLM(n_input, n_hidden, n_output);
                    bplm.trainBPLM(train, learning_rate, maxEpoch, 0.1);
                    //bplm.trainBPLM(train, learning_rate, maxEpoch, 0.1, cfBPLM);
                    TableData.setModel(SetTable(true, true));
                    LabelData.setText("Data Pelatihan");
                    type = 2;
                    LabelPelatihan.setText("Pelatihan : BPLM");
                    //cfBPLM.savePerformance2(true, counter);
                    //JOptionPane.showMessageDialog(null, "Training Selesai");
                } else {
                    JOptionPane.showMessageDialog(null, "Silahkan pilih metode");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Learning rate tidak dalam range.\nSilahkan masukkan nilai yang tepat");
            }
            ButtonTest.setEnabled(true);
        }
    }//GEN-LAST:event_ButtonTrainActionPerformed

    private void ButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTestActionPerformed
        // TODO add your handling code here:
        test = set.createTestData(0.2f);
        
        switch (type) {
            case 1:
                ConfusionMatrix cfBP = new ConfusionMatrix();
                bp.test(test, cfBP);
                TableData.setModel(SetTable(false, false));
                LabelData.setText("Data Pengujian");
                LabelAkurasi.setText("Akurasi : "+String.valueOf(String.format("%.2f", cfBP.getAccuracy())));
                LabelSpesifisitas.setText("Spesifisitas : "+String.valueOf(String.format("%.2f", cfBP.getSpecificity())));
                LabelSensitifitas.setText("Sensitifitas : "+String.valueOf(String.format("%.2f", cfBP.getSensitivity())));
                LabelPresisi.setText("Presisi : "+String.valueOf(String.format("%.2f", cfBP.getPrecision())));
                LabelFMeasure.setText("FMeasure : "+String.valueOf(String.format("%.2f", cfBP.getFmeasure())));
                //JOptionPane.showMessageDialog(null, "Testing Selesai");
                //bp.printWeights();
                //cfBP.savePerformance(false, counter);
                break;
            case 2:
                ConfusionMatrix cfBPLM = new ConfusionMatrix();
                bplm.test(test, cfBPLM);
                TableData.setModel(SetTable(false, true));
                LabelData.setText("Data Pengujian");
                LabelAkurasi.setText("Akurasi : "+String.valueOf(String.format("%.2f", cfBPLM.getAccuracy())));
                LabelSpesifisitas.setText("Spesifisitas : "+String.valueOf(String.format("%.2f", cfBPLM.getSpecificity())));
                LabelSensitifitas.setText("Sensitifitas : "+String.valueOf(String.format("%.2f", cfBPLM.getSensitivity())));
                LabelPresisi.setText("Presisi : "+String.valueOf(String.format("%.2f", cfBPLM.getPrecision())));
                LabelFMeasure.setText("FMeasure : "+String.valueOf(String.format("%.2f", cfBPLM.getFmeasure())));
                //JOptionPane.showMessageDialog(null, "Testing Selesai");
                //bplm.printWeights();
                //cfBPLM.savePerformance(true, counter);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Lakukan training terlebih dahulu");
                break;
        }
    }//GEN-LAST:event_ButtonTestActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI ui = new UI();
                ui.setVisible(true);
                ui.setLocationRelativeTo(null);
                ui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTest;
    private javax.swing.JButton ButtonTrain;
    private javax.swing.JLabel LabelAkurasi;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelEpoch;
    private javax.swing.JLabel LabelFMeasure;
    private javax.swing.JLabel LabelLRate;
    private javax.swing.JLabel LabelPelatihan;
    private javax.swing.JLabel LabelPresisi;
    private javax.swing.JLabel LabelSensitifitas;
    private javax.swing.JLabel LabelSpesifisitas;
    private javax.swing.JLabel LabelTesting;
    private javax.swing.JLabel LabelTraining;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JRadioButton RadioButtonBP;
    private javax.swing.JRadioButton RadioButtonBPLM;
    private javax.swing.JTextField TFieldEpoch;
    private javax.swing.JTextField TFieldLRate;
    private javax.swing.JTable TableData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
